<template>
  <component :is="iconComponent" :class="className" aria-hidden="true" />
</template>

<script setup>
import { computed } from "vue";
import {
  ArrowRight,
  BookOpen,
  CreditCard,
  Briefcase,
  Building2,
  Bus,
  Camera,
  CalendarDays,
  Gift,
  ChartColumn,
  Heart,
  Hotel,
  ChartPie,
  Circle,
  CircleDollarSign,
  ExternalLink,
  Music,
  Flame,
  Package,
  FolderKanban,
  Gem,
  Shirt,
  Github,
  Landmark,
  Mail,
  MessageCircle,
  Mic,
  Palette,
  Search,
  Users,
  VolumeX,
  Wallet,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquarePen,
  Store,
  Target,
  WandSparkles,
  Wrench,
  Zap,
  Check,
  X,
  Rocket,
} from "lucide-vue-next";

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  className: {
    type: String,
    default: "w-5 h-5",
  },
});

const iconMap = {
  "arrow-right": ArrowRight,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  bus: Bus,
  camera: Camera,
  "calendar-days": CalendarDays,
  "chart-column": ChartColumn,
  "chart-pie": ChartPie,
  "circle-dollar-sign": CircleDollarSign,
  "credit-card": CreditCard,
  "external-link": ExternalLink,
  flame: Flame,
  "folder-kanban": FolderKanban,
  gem: Gem,
  gift: Gift,
  github: Github,
  heart: Heart,
  hotel: Hotel,
  landmark: Landmark,
  mail: Mail,
  "message-circle": MessageCircle,
  mic: Mic,
  music: Music,
  palette: Palette,
  package: Package,
  rocket: Rocket,
  search: Search,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  store: Store,
  target: Target,
  users: Users,
  "volume-x": VolumeX,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  wrench: Wrench,
  zap: Zap,
  check: Check,
  x: X,
};

const iconComponent = computed(() => iconMap[props.name] || Circle);
</script>
