<template>
  <component :is="iconComponent" :class="className" aria-hidden="true" />
</template>

<script setup>
import { computed } from "vue";
import {
  ArrowRight,
  ArrowLeft,
  BookOpen,
  Building,
  Calendar,
  CreditCard,
  Briefcase,
  Building2,
  Bus,
  Camera,
  CalendarDays,
  ChefHat,
  Gift,
  ChartColumn,
  Heart,
  Hotel,
  ChartPie,
  Circle,
  CircleDollarSign,
  ExternalLink,
  Eye,
  Music,
  Flame,
  ImagePlus,
  Images,
  Layout,
  Package,
  PackageCheck,
  FolderKanban,
  Gem,
  PartyPopper,
  Ruler,
  Salad,
  Shirt,
  Github,
  Landmark,
  Mail,
  MessageCircle,
  Mic,
  Palette,
  Search,
  SearchX,
  Share2,
  Tag,
  Truck,
  Users,
  UtensilsCrossed,
  VolumeX,
  Wallet,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquarePen,
  Store,
  Target,
  WandSparkles,
  Wrench,
  Zap,
  Check,
  X,
  Rocket,
  MousePointerClick,
  Filter,
  UserCircle,
  FlaskConical,
  Magnet,
  Mails,
  Bot,
  BarChart3,
  Users2,
  MessageSquare,
  Calculator,
  FileText,
  Puzzle,
  Workflow,
  LayoutDashboard,
  Boxes,
  Contact,
  PackageSearch,
  LifeBuoy,
  Repeat,
  Network,
  BrainCircuit,
  PenTool,
  LineChart,
  Cpu,
  LayoutTemplate,
  Utensils,
  PieChart,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  MapPin,
  Play,
  Ticket,
  Bird,
  Baby,
  Smile,
  Dices,
  QrCode,
  Volume2,
  House,
  Clock,
  Shield,
  Star,
  Globe,
  TrendingUp,
  Image,
  Tent,
  Award,
  Server,
  Settings2,
  BadgeCheck,
  ShieldCheck,
  CircleCheck,
  Code,
  Code2,
  Gauge,
  Megaphone,
  Banknote,
  Plug,
  Scan,
  CalendarCheck,
  Instagram,
  Percent,
  Equal,
  Plus,
  Minus,
  DollarSign,
  Send,
  FileSearch,
  Linkedin,
  Quote,
  ChevronUp,
  ArrowUpRight,
  Lightbulb,
  Compass,
  Rocket as RocketIcon,
  Hammer,
  PartyPopper as PartyIcon,
  CheckCircle2,
  TimerReset,
  Clock4,
} from "lucide-vue-next";

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  className: {
    type: String,
    default: "w-5 h-5",
  },
});

const iconMap = {
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  bus: Bus,
  calendar: Calendar,
  camera: Camera,
  "calendar-days": CalendarDays,
  "chef-hat": ChefHat,
  "chart-column": ChartColumn,
  "chart-pie": ChartPie,
  "circle-dollar-sign": CircleDollarSign,
  "credit-card": CreditCard,
  "external-link": ExternalLink,
  eye: Eye,
  flame: Flame,
  "folder-kanban": FolderKanban,
  gem: Gem,
  gift: Gift,
  github: Github,
  heart: Heart,
  hotel: Hotel,
  "image-plus": ImagePlus,
  images: Images,
  landmark: Landmark,
  layout: Layout,
  mail: Mail,
  "message-circle": MessageCircle,
  mic: Mic,
  music: Music,
  "package-check": PackageCheck,
  palette: Palette,
  package: Package,
  "party-popper": PartyPopper,
  rocket: Rocket,
  ruler: Ruler,
  salad: Salad,
  search: Search,
  "search-x": SearchX,
  "share-2": Share2,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  store: Store,
  tag: Tag,
  target: Target,
  truck: Truck,
  users: Users,
  "utensils-crossed": UtensilsCrossed,
  "volume-x": VolumeX,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  wrench: Wrench,
  zap: Zap,
  check: Check,
  x: X,
  "mouse-pointer-click": MousePointerClick,
  filter: Filter,
  "user-circle": UserCircle,
  "flask-conical": FlaskConical,
  magnet: Magnet,
  mails: Mails,
  bot: Bot,
  "bar-chart-3": BarChart3,
  "users-2": Users2,
  "message-square": MessageSquare,
  calculator: Calculator,
  "file-text": FileText,
  puzzle: Puzzle,
  workflow: Workflow,
  "layout-dashboard": LayoutDashboard,
  boxes: Boxes,
  contact: Contact,
  "package-search": PackageSearch,
  "life-buoy": LifeBuoy,
  repeat: Repeat,
  network: Network,
  "brain-circuit": BrainCircuit,
  "pen-tool": PenTool,
  "line-chart": LineChart,
  cpu: Cpu,
  "layout-template": LayoutTemplate,
  utensils: Utensils,
  "pie-chart": PieChart,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "map-pin": MapPin,
  play: Play,
  ticket: Ticket,
  bird: Bird,
  baby: Baby,
  smile: Smile,
  dices: Dices,
  "qr-code": QrCode,
  "volume-2": Volume2,
  house: House,
  clock: Clock,
  shield: Shield,
  star: Star,
  globe: Globe,
  "trending-up": TrendingUp,
  image: Image,
  tent: Tent,
  award: Award,
  server: Server,
  "settings-2": Settings2,
  "badge-check": BadgeCheck,
  "shield-check": ShieldCheck,
  "circle-check": CircleCheck,
  code: Code,
  "code-2": Code2,
  gauge: Gauge,
  megaphone: Megaphone,
  banknote: Banknote,
  plug: Plug,
  scan: Scan,
  "calendar-check": CalendarCheck,
  instagram: Instagram,
  percent: Percent,
  equal: Equal,
  plus: Plus,
  minus: Minus,
  "dollar-sign": DollarSign,
  send: Send,
  "file-search": FileSearch,
  linkedin: Linkedin,
  quote: Quote,
  "chevron-up": ChevronUp,
  "arrow-up-right": ArrowUpRight,
  lightbulb: Lightbulb,
  compass: Compass,
  hammer: Hammer,
  "check-circle-2": CheckCircle2,
  "timer-reset": TimerReset,
  "clock-4": Clock4,
};

const iconComponent = computed(() => iconMap[props.name] || Circle);
</script>
