<template>
  <component :is="iconComponent" :class="className" aria-hidden="true" />
</template>

<script setup>
import { computed } from "vue";
import {
  ArrowRight,
  ArrowLeft,
  BookOpen,
  CreditCard,
  Briefcase,
  Building2,
  Bus,
  Camera,
  CalendarDays,
  Gift,
  ChartColumn,
  Heart,
  Hotel,
  ChartPie,
  Circle,
  CircleDollarSign,
  ExternalLink,
  Music,
  Flame,
  Package,
  FolderKanban,
  Gem,
  Shirt,
  Github,
  Landmark,
  Mail,
  MessageCircle,
  Mic,
  Palette,
  Search,
  Users,
  VolumeX,
  Wallet,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquarePen,
  Store,
  Target,
  WandSparkles,
  Wrench,
  Zap,
  Check,
  X,
  Rocket,
  MousePointerClick,
  Filter,
  UserCircle,
  FlaskConical,
  Magnet,
  Mails,
  Bot,
  BarChart3,
  Users2,
  MessageSquare,
  Calculator,
  FileText,
  Puzzle,
  Workflow,
  LayoutDashboard,
  Boxes,
  Contact,
  PackageSearch,
  LifeBuoy,
  Repeat,
  Network,
  BrainCircuit,
  PenTool,
  LineChart,
  Cpu,
  LayoutTemplate,
  Utensils,
  PieChart,
  ChevronLeft,
  ChevronDown,
  MapPin,
  Play,
  Ticket,
  Bird,
  Baby,
  Smile,
  Dices,
  QrCode,
  Volume2,
  House
} from "lucide-vue-next";

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  className: {
    type: String,
    default: "w-5 h-5",
  },
});

const iconMap = {
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  bus: Bus,
  camera: Camera,
  "calendar-days": CalendarDays,
  "chart-column": ChartColumn,
  "chart-pie": ChartPie,
  "circle-dollar-sign": CircleDollarSign,
  "credit-card": CreditCard,
  "external-link": ExternalLink,
  flame: Flame,
  "folder-kanban": FolderKanban,
  gem: Gem,
  gift: Gift,
  github: Github,
  heart: Heart,
  hotel: Hotel,
  landmark: Landmark,
  mail: Mail,
  "message-circle": MessageCircle,
  mic: Mic,
  music: Music,
  palette: Palette,
  package: Package,
  rocket: Rocket,
  search: Search,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  store: Store,
  target: Target,
  users: Users,
  "volume-x": VolumeX,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  wrench: Wrench,
  zap: Zap,
  check: Check,
  x: X,
  "mouse-pointer-click": MousePointerClick,
  filter: Filter,
  "user-circle": UserCircle,
  "flask-conical": FlaskConical,
  magnet: Magnet,
  mails: Mails,
  bot: Bot,
  "bar-chart-3": BarChart3,
  "users-2": Users2,
  "message-square": MessageSquare,
  calculator: Calculator,
  "file-text": FileText,
  puzzle: Puzzle,
  workflow: Workflow,
  "layout-dashboard": LayoutDashboard,
  boxes: Boxes,
  contact: Contact,
  "package-search": PackageSearch,
  "life-buoy": LifeBuoy,
  repeat: Repeat,
  network: Network,
  "brain-circuit": BrainCircuit,
  "pen-tool": PenTool,
  "line-chart": LineChart,
  cpu: Cpu,
  "layout-template": LayoutTemplate,
  utensils: Utensils,
  "pie-chart": PieChart,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "map-pin": MapPin,
  play: Play,
  ticket: Ticket,
  bird: Bird,
  baby: Baby,
  smile: Smile,
  dices: Dices,
  "qr-code": QrCode,
  "volume-2": Volume2,
  house: House
};

const iconComponent = computed(() => iconMap[props.name] || Circle);
</script>
